/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewExamIdRouteImport } from './routes/review.$examId'
import { Route as ResultExamIdRouteImport } from './routes/result.$examId'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewExamIdRoute = ReviewExamIdRouteImport.update({
  id: '/review/$examId',
  path: '/review/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultExamIdRoute = ResultExamIdRouteImport.update({
  id: '/result/$examId',
  path: '/result/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/result/$examId': typeof ResultExamIdRoute
  '/review/$examId': typeof ReviewExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam/$examId' | '/result/$examId' | '/review/$examId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$examId' | '/result/$examId' | '/review/$examId'
  id: '__root__' | '/' | '/exam/$examId' | '/result/$examId' | '/review/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  ResultExamIdRoute: typeof ResultExamIdRoute
  ReviewExamIdRoute: typeof ReviewExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$examId': {
      id: '/review/$examId'
      path: '/review/$examId'
      fullPath: '/review/$examId'
      preLoaderRoute: typeof ReviewExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$examId': {
      id: '/result/$examId'
      path: '/result/$examId'
      fullPath: '/result/$examId'
      preLoaderRoute: typeof ResultExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  ResultExamIdRoute: ResultExamIdRoute,
  ReviewExamIdRoute: ReviewExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
